// Psychology ICD-10 diagnosis library, extracted from TIFEC's Psychology_ICD10_Library.pdf
// and normalized to ICD-10-CM decimal form (e.g. F320 -> F32.0). Range/category rows
// (e.g. F10-F19) are flagged and are NOT selectable as a single diagnosis.
export interface Icd10Code { code: string; description: string; category: string; range?: boolean }

export const ICD10: Icd10Code[] = [
  { code: "F40.1", description: "Social Anxiety Disorder", category: "Anxiety Disorders" },
  { code: "F40.01", description: "Agoraphobia with panic disorder", category: "Anxiety Disorders" },
  { code: "F40.02", description: "Agoraphobia without panic disorder", category: "Anxiety Disorders" },
  { code: "F41.2", description: "Mixed Anxiety and Depressive Disorder", category: "Anxiety Disorders" },
  { code: "F41.0", description: "Panic disorder [episodic paroxysmal anxiety]", category: "Anxiety Disorders" },
  { code: "F41.1", description: "Generalized anxiety disorder", category: "Anxiety Disorders" },
  { code: "F41.9", description: "Anxiety Disorder", category: "Anxiety Disorders" },
  { code: "F32.0", description: "Major depressive disorder, single episode, mild", category: "Depressive Disorders" },
  { code: "F32.1", description: "Major depressive disorder, single episode, moderate", category: "Depressive Disorders" },
  { code: "F32.2", description: "Major depressive disorder, single episode, severe without psychotic features", category: "Depressive Disorders" },
  { code: "F32.3", description: "Major depressive disorder, single episode, severe with psychotic features", category: "Depressive Disorders" },
  { code: "F32.4", description: "Major depressive disorder, single episode, in partial remission", category: "Depressive Disorders" },
  { code: "F32.5", description: "Major depressive disorder, single episode, in full remission", category: "Depressive Disorders" },
  { code: "F32.9", description: "Major depressive disorder, single episode, unspecified", category: "Depressive Disorders" },
  { code: "F33.0", description: "Major depressive disorder, recurrent, mild", category: "Depressive Disorders" },
  { code: "F33.1", description: "Major depressive disorder, recurrent, moderate", category: "Depressive Disorders" },
  { code: "F33.2", description: "Major depressive disorder, recurrent severe without psychotic features", category: "Depressive Disorders" },
  { code: "F33.3", description: "Major depressive disorder, recurrent, severe with psychotic symptoms", category: "Depressive Disorders" },
  { code: "F33.41", description: "Major depressive disorder, recurrent, in partial remission", category: "Depressive Disorders" },
  { code: "F33.42", description: "Major depressive disorder, recurrent, in full remission", category: "Depressive Disorders" },
  { code: "F34.0", description: "Cyclothymic disorder", category: "Depressive Disorders" },
  { code: "F34.1", description: "Dysthymic disorder", category: "Depressive Disorders" },
  { code: "F31.11", description: "Bipolar disorder, current manic episode, mild", category: "Bipolar Disorders" },
  { code: "F31.12", description: "Bipolar disorder, current manic episode, moderate", category: "Bipolar Disorders" },
  { code: "F31.13", description: "Bipolar disorder, current manic episode, severe", category: "Bipolar Disorders" },
  { code: "F31.2", description: "Bipolar disorder, current manic episode, severe with psychotic features", category: "Bipolar Disorders" },
  { code: "F31.31", description: "Bipolar disorder, current depressed episode, mild", category: "Bipolar Disorders" },
  { code: "F31.32", description: "Bipolar disorder, current depressed episode, moderate", category: "Bipolar Disorders" },
  { code: "F31.4", description: "Bipolar disorder, current depressed episode, severe without psychotic features", category: "Bipolar Disorders" },
  { code: "F31.5", description: "Bipolar disorder, current depressed episode, severe with psychotic features", category: "Bipolar Disorders" },
  { code: "F3161–F3164", description: "Bipolar disorder, current mixed episode", category: "Bipolar Disorders", range: true },
  { code: "F3173–F3178", description: "Bipolar disorder, various remission states", category: "Bipolar Disorders", range: true },
  { code: "F31.81", description: "Bipolar II disorder", category: "Bipolar Disorders" },
  { code: "F31.9", description: "Bipolar disorder, unspecified", category: "Bipolar Disorders" },
  { code: "F43.0", description: "Acute stress reaction", category: "Trauma, Stress & Adjustment" },
  { code: "F43.10", description: "Post-traumatic stress disorder", category: "Trauma, Stress & Adjustment" },
  { code: "F43.20", description: "Adjustment disorder, unspecified", category: "Trauma, Stress & Adjustment" },
  { code: "F43.22", description: "Adjustment disorder with anxiety", category: "Trauma, Stress & Adjustment" },
  { code: "F43.23", description: "Adjustment disorder with mixed anxiety and depressed mood", category: "Trauma, Stress & Adjustment" },
  { code: "F43.24", description: "Adjustment disorder with disturbance of conduct", category: "Trauma, Stress & Adjustment" },
  { code: "F43.25", description: "Adjustment disorder with mixed disturbance of emotions and conduct", category: "Trauma, Stress & Adjustment" },
  { code: "F43.81", description: "Prolonged grief", category: "Trauma, Stress & Adjustment" },
  { code: "F42", description: "Obsessive-compulsive disorder", category: "Obsessive-Compulsive & Related" },
  { code: "F45.21", description: "Hypochondriasis", category: "Obsessive-Compulsive & Related" },
  { code: "F45.22", description: "Body dysmorphic disorder", category: "Obsessive-Compulsive & Related" },
  { code: "F63.3", description: "Trichotillomania", category: "Obsessive-Compulsive & Related" },
  { code: "F44.0", description: "Dissociative amnesia", category: "Dissociative & Conversion" },
  { code: "F44.1", description: "Dissociative fugue", category: "Dissociative & Conversion" },
  { code: "F44.4", description: "Conversion disorder with motor symptom or deficit", category: "Dissociative & Conversion" },
  { code: "F44.6", description: "Conversion disorder with sensory symptom or deficit", category: "Dissociative & Conversion" },
  { code: "F44.81", description: "Dissociative identity disorder", category: "Dissociative & Conversion" },
  { code: "F44.89", description: "Other dissociative and conversion disorders", category: "Dissociative & Conversion" },
  { code: "F44.9", description: "Dissociative and conversion disorder, unspecified", category: "Dissociative & Conversion" },
  { code: "F48.1", description: "Depersonalization-derealization syndrome", category: "Dissociative & Conversion" },
  { code: "F50.00", description: "Anorexia nervosa, unspecified", category: "Eating Disorders" },
  { code: "F50.2", description: "Bulimia nervosa", category: "Eating Disorders" },
  { code: "F50.8", description: "Other eating disorders", category: "Eating Disorders" },
  { code: "F50.82", description: "Avoidant/restrictive food intake disorder", category: "Eating Disorders" },
  { code: "F51.01", description: "Primary insomnia", category: "Sleep Disorders" },
  { code: "F51.03", description: "Paradoxical insomnia", category: "Sleep Disorders" },
  { code: "F51.09", description: "Other insomnia not due to a substance or known physiological condition", category: "Sleep Disorders" },
  { code: "F51.11", description: "Primary hypersomnia", category: "Sleep Disorders" },
  { code: "F51.12", description: "Insufficient sleep syndrome", category: "Sleep Disorders" },
  { code: "F51.19", description: "Other hypersomnia not due to a substance or known physiological condition", category: "Sleep Disorders" },
  { code: "F51.8", description: "Other sleep disorders not due to a substance or known physiological condition", category: "Sleep Disorders" },
  { code: "F60.2", description: "Antisocial personality disorder", category: "Personality Disorders" },
  { code: "F60.3", description: "Borderline personality disorder", category: "Personality Disorders" },
  { code: "F60.5", description: "Obsessive-compulsive personality disorder", category: "Personality Disorders" },
  { code: "F60.6", description: "Avoidant personality disorder", category: "Personality Disorders" },
  { code: "F60.7", description: "Dependent personality disorder", category: "Personality Disorders" },
  { code: "F60.81", description: "Narcissistic personality disorder", category: "Personality Disorders" },
  { code: "F60.9", description: "Personality disorder, unspecified", category: "Personality Disorders" },
  { code: "F68.8", description: "Other specified disorders of adult personality and behavior", category: "Personality Disorders" },
  { code: "F63.0", description: "Pathological gambling", category: "Behavioral / Impulse-Control" },
  { code: "F63.2", description: "Kleptomania", category: "Behavioral / Impulse-Control" },
  { code: "F63.81", description: "Intermittent explosive disorder", category: "Behavioral / Impulse-Control" },
  { code: "F68.11", description: "Factitious disorder with predominantly psychological signs and symptoms", category: "Behavioral / Impulse-Control" },
  { code: "F80.0", description: "Phonological disorder", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F80.1", description: "Expressive language disorder", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F80.2", description: "Mixed receptive-expressive language disorder", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F81.0", description: "Specific reading disorder", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F81.2", description: "Mathematics disorder", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F81.81", description: "Disorder of written expression", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F81.9", description: "Developmental disorder of scholastic skills, unspecified", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F82", description: "Specific developmental disorder of motor function", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F84.0", description: "Autistic disorder", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F84.5", description: "Asperger's syndrome", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F84.8", description: "Other pervasive developmental disorders", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F84.9", description: "Pervasive developmental disorder, unspecified", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F88", description: "Other disorders of psychological development", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F89", description: "Unspecified disorder of psychological development", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F90.0", description: "ADHD, predominantly inattentive type", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F90.1", description: "ADHD, predominantly hyperactive type", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F90.2", description: "ADHD, combined type", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F90.8", description: "ADHD, other type", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F90.9", description: "ADHD, unspecified type", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F91.1", description: "Conduct disorder, childhood-onset type", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F91.2", description: "Conduct disorder, adolescent-onset type", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F91.3", description: "Oppositional defiant disorder", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F91.8", description: "Other conduct disorders", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F91.9", description: "Conduct disorder, unspecified", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F93", description: "Separation anxiety disorder", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F93.8", description: "Other childhood emotional disorders", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F93.9", description: "Childhood emotional disorder, unspecified", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F94.0", description: "Selective mutism", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F94.8", description: "Other childhood disorders of social functioning", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F98.9", description: "Unspecified behavioral and emotional disorders with onset usually occurring in childhood and adolescence", category: "Neurodevelopmental & Child/Adolescent" },
  { code: "F10–F19", description: "Substance-related and addictive disorders represented in the source list, including alcohol, cannabis,", category: "Substance-Related & Addictive Disorders", range: true },
  { code: "F12.180", description: "Cannabis abuse with cannabis-induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F12.280", description: "Cannabis dependence with cannabis-induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F12.980", description: "Cannabis use, unspecified with anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F13.180", description: "Sedative, hypnotic or anxiolytic abuse with induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F13.280", description: "Sedative, hypnotic or anxiolytic dependence with induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F14.180", description: "Cocaine abuse with cocaine-induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F14.280", description: "Cocaine dependence with cocaine-induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F14.980", description: "Cocaine use, unspecified with cocaine-induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F15.180", description: "Other stimulant abuse with stimulant-induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F15.280", description: "Other stimulant dependence with stimulant-induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F15.980", description: "Other stimulant use, unspecified with stimulant-induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F16.180", description: "Hallucinogen abuse with hallucinogen-induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F16.280", description: "Hallucinogen dependence with hallucinogen-induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F16.980", description: "Hallucinogen use, unspecified with hallucinogen-induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F18.180", description: "Inhalant abuse with inhalant-induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F18.280", description: "Inhalant dependence with inhalant-induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F18.980", description: "Inhalant use, unspecified with inhalant-induced anxiety disorder", category: "Substance-Related & Addictive Disorders" },
  { code: "F54", description: "Psychological and behavioral factors associated with disorders or diseases classified elsewhere", category: "Psychological Factors / Sexual Function" },
  { code: "F52.0", description: "Hypoactive sexual desire disorder", category: "Psychological Factors / Sexual Function" },
  { code: "F52.21", description: "Male erectile disorder", category: "Psychological Factors / Sexual Function" },
  { code: "F52.31", description: "Female orgasmic disorder", category: "Psychological Factors / Sexual Function" },
  { code: "F52.32", description: "Male orgasmic disorder", category: "Psychological Factors / Sexual Function" },
  { code: "F52.6", description: "Dyspareunia not due to a substance or known physiological condition", category: "Psychological Factors / Sexual Function" },
  { code: "F52.8", description: "Other sexual dysfunction not due to a substance or known physiological condition", category: "Psychological Factors / Sexual Function" },
  { code: "F20", description: "Schizophrenia category represented in the source list", category: "Psychotic Disorders" },
  { code: "F22", description: "Delusional disorder", category: "Psychotic Disorders" },
  { code: "F23", description: "Brief psychotic disorder", category: "Psychotic Disorders" },
  { code: "F25.9", description: "Schizoaffective disorder", category: "Psychotic Disorders" },
  { code: "F29", description: "Unspecified psychosis", category: "Psychotic Disorders" },
  { code: "Z55.9", description: "Problems related to education and literacy, unspecified", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z60.3", description: "Acculturation difficulty", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z62.891", description: "Sibling rivalry", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z63.0", description: "Problems in relationship with spouse or partner", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z63.4", description: "Uncomplicated bereavement", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z63.8", description: "Other specified problems related to primary support group", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z63.9", description: "Problem related to primary support group, unspecified", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z65.8", description: "Other specified problems related to psychosocial circumstances", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z69.020", description: "Encounter for mental health services for non-parental child sexual abuse", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z69.010", description: "Encounter for mental health services for victim of parental child abuse", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z69.011", description: "Encounter for mental health services for perpetrator of parental child abuse", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z69.021", description: "Encounter for mental health services for perpetrator of non-parental child abuse", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z69.11", description: "Encounter for mental health services for victim of spousal or partner abuse", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z69.12", description: "Encounter for mental health services for perpetrator of spousal or partner abuse", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z69.82", description: "Encounter for mental health services for perpetrator of other abuse", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z71.89", description: "Other specified counseling", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z73.5", description: "Peer conflict", category: "Psychosocial & Counseling Z-Codes" },
  { code: "Z86.59", description: "Personal history of other mental and behavioral disorders", category: "Psychosocial & Counseling Z-Codes" },
];

export const ICD10_CATEGORIES = ["Anxiety Disorders", "Depressive Disorders", "Bipolar Disorders", "Trauma, Stress & Adjustment", "Obsessive-Compulsive & Related", "Dissociative & Conversion", "Eating Disorders", "Sleep Disorders", "Personality Disorders", "Behavioral / Impulse-Control", "Neurodevelopmental & Child/Adolescent", "Substance-Related & Addictive Disorders", "Psychological Factors / Sexual Function", "Psychotic Disorders", "Psychosocial & Counseling Z-Codes"];

// Clinical acronyms / common short names → code(s), so "PTSD", "OCD", "GAD" etc.
// resolve to the right diagnosis even though the formal descriptions don't spell
// out the acronym. Only codes that exist in the library above are listed.
export const ICD10_ALIASES: Record<string, string[]> = {
  ptsd: ["F43.10"], ocd: ["F42"], gad: ["F41.1"], mdd: ["F32.9", "F32.0", "F33.0"],
  bpd: ["F60.3"], ocpd: ["F60.5"], odd: ["F91.3"], asd: ["F84.0"], add: ["F90.0"],
  adhd: ["F90.9", "F90.0", "F90.1", "F90.2"], ied: ["F63.81"], did: ["F44.81"],
  bipolar: ["F31.9"], panic: ["F41.0"], insomnia: ["F51.01"], hypersomnia: ["F51.11"],
  anorexia: ["F50.00"], bulimia: ["F50.2"], arfid: ["F50.82"], bdd: ["F45.22"],
  agoraphobia: ["F40.01", "F40.02"], grief: ["F43.81"], bereavement: ["Z63.4"],
  autism: ["F84.0"], asperger: ["F84.5"], dysthymia: ["F34.1"], cyclothymia: ["F34.0"],
  ed: ["F50.00", "F50.2", "F50.82"], gd: ["F63.0"], schizophrenia: ["F20"],
};
